environment:
  build_version: 6.1.0
  Version: $(build_version)-Nightly%APPVEYOR_BUILD_NUMBER%
version: $(build_version)-{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(build_version).0'
  assembly_file_version: '$(build_version).{build}'
  assembly_informational_version: '$(build_version)'
before_build:
 - cmd: nuget restore DependencyInjection.sln
build:
  project: DependencyInjection.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
after_build:
- cmd: msbuild /t:pack src/Grace.AspNetCore.Hosting/Grace.AspNetCore.Hosting.csproj /p:Configuration=Release /p:IncludeSymbols=true /p:PackageOutputPath=..\..\
- cmd: msbuild /t:pack src/Grace.AspNetCore.MVC/Grace.AspNetCore.MVC.csproj /p:Configuration=Release /p:IncludeSymbols=true /p:PackageOutputPath=..\..\
- cmd: msbuild /t:pack src/Grace.DependencyInjection.Extensions/Grace.DependencyInjection.Extensions.csproj /p:Configuration=Release /p:IncludeSymbols=true /p:PackageOutputPath=..\..\
artifacts:
- path: Grace*.nupkg
  name: Grace
os: Visual Studio 2017